version: '3.9'

services:
  jenkins:
    privileged: true
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # UNIX socket to which the docker daemon is connected
    env_file:
     - .env

  registry:
    restart: always
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data