apiVersion: apps/v1
kind: Deployment
metadata:
  name: whanos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whanos
  template:
    metadata:
      labels:
        app: whanos
    spec:
      containers:
      - name: whanos
        image: whanos:latest
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
