# syntax=docker/dockerfile:1
FROM maven:3.8.4-jdk-11-slim AS builder
COPY . /app
WORKDIR /app
RUN mvn dependency:resolve -f app/pom.xml
RUN mvn package -f app/pom.xml
RUN rm -rf app/


FROM openjdk:11-jre-slim
SHELL ["/bin/bash", "-c"]
COPY --from=builder app/target/app.jar .
CMD ["java", "-jar", "app.jar"]
