# syntax=docker/dockerfile:1
FROM maven:3.8.4-jdk-11-slim AS builder
SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app
ONBUILD WORKDIR /app
ONBUILD RUN mvn dependency:resolve -f app/pom.xml
ONBUILD RUN mvn package -f app/pom.xml
ONBUILD RUN rm -rf app/


FROM openjdk:11-jre-slim
SHELL ["/bin/bash", "-c"]
ONBUILD COPY --from=builder app/target/app.jar .
ONBUILD CMD ["java", "-jar", "app.jar"]
